cartpole-ppo-kl-tuning:
    env: CartPole-v1
    run: PPO
    stop:
        episode_reward_mean: 150
        timesteps_total: 100000
    config:
        # Works for both torch and tf.
        seed: 0
        framework:
            grid_search:
                - tf2
                # - torch
        gamma: 0.99
        lr: 
            grid_search:
                - 0.001
        num_workers: 0
        observation_filter: MeanStdFilter
        num_sgd_iter: 6
        vf_loss_coeff: 0.01
        model:
            fcnet_hiddens: [32, 32]
            fcnet_activation: linear
            # vf_share_layers: true
        enable_connectors: true
        _enable_rl_module_api:
            grid_search:
                - true
                - false
